package UserInterface.WorkAreas.RegistrarRole;


import Business.Business;
import Business.CourseSchedule.CourseOffer;
import Business.CourseSchedule.CourseSchedule;
import Business.Department.Department;
import Business.CourseCatalog.Course;

import Business.Person.Faculty.FacultyProfile;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class CreateCourseOfferingJPanel extends javax.swing.JPanel {

    private Business business;
    private JPanel CardSequencePanel;

    /**
     * Creates new form CreateCourseOfferingJPanel
     * @param b The business object.
     * @param cardSequencePanel The main panel for navigation.
     */
    public CreateCourseOfferingJPanel(Business b, JPanel cardSequencePanel) {
        initComponents();
        this.business = b;
        this.CardSequencePanel = cardSequencePanel;
        populateCombos();
    }

    private void populateCombos() {
        // Populate Course ComboBox
        DefaultComboBoxModel<Course> courseModel = new DefaultComboBoxModel<>();
        for (Department dept : business.getUniversity().getDepartmentDirectory().getDepartmentList()) {
            for (Course course : dept.getCourseCatalog().getCourseList()) {
                courseModel.addElement(course);
            }
        }
        comboCourse.setModel(courseModel);

        // Populate Faculty ComboBox
        DefaultComboBoxModel<FacultyProfile> facultyModel = new DefaultComboBoxModel<>();
        // This is a simplified approach; assumes FacultyDirectory exists on Department.
        // You may need to adjust the path to your FacultyDirectory.
        for (Department dept : business.getUniversity().getDepartmentDirectory().getDepartmentList()) {
            if (dept.getFacultyDirectory() != null) {
                for (FacultyProfile fp : dept.getFacultyDirectory().getTeacherlist()) {
                    facultyModel.addElement(fp);
                }
            }
        }
        comboFaculty.setModel(facultyModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        comboCourse = new javax.swing.JComboBox<>();
        lblFaculty = new javax.swing.JLabel();
        comboFaculty = new javax.swing.JComboBox<>();
        lblSemester = new javax.swing.JLabel();
        comboSemester = new javax.swing.JComboBox<>();
        lblSeatLimit = new javax.swing.JLabel();
        txtSeatLimit = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create New Course Offering");

        lblCourse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCourse.setText("Course:");

        lblFaculty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFaculty.setText("Professor:");

        lblSemester.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSemester.setText("Semester:");

        comboSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2024", "Spring 2025", "Fall 2025", "Spring 2026" }));

        lblSeatLimit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSeatLimit.setText("Seat Limit:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btnBack))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(lblFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblSeatLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(comboCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(comboFaculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(comboSemester, 0, 200, Short.MAX_VALUE)
                                                                                .addComponent(txtSeatLimit)))))))
                                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(lblTitle)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCourse)
                                        .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFaculty)
                                        .addComponent(comboFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSemester)
                                        .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSeatLimit)
                                        .addComponent(txtSeatLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(btnSave)
                                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate back to the previous panel
        CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Get user input from UI components
        Course selectedCourse = (Course) comboCourse.getSelectedItem();
        FacultyProfile selectedFaculty = (FacultyProfile) comboFaculty.getSelectedItem();
        String selectedSemester = (String) comboSemester.getSelectedItem();
        String seatLimitStr = txtSeatLimit.getText();

        // 2. Validate input
        if (selectedCourse == null || selectedFaculty == null) {
            JOptionPane.showMessageDialog(this, "Please make a selection for Course and Professor.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int seatLimit;
        try {
            seatLimit = Integer.parseInt(seatLimitStr);
            if (seatLimit <= 0) {
                JOptionPane.showMessageDialog(this, "Seat Limit must be a positive number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for Seat Limit.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Find the department that owns the selected course
        Department ownerDepartment = findDepartmentForCourse(selectedCourse);
        if (ownerDepartment == null) {
            JOptionPane.showMessageDialog(this, "Could not find the department for the selected course.", "System Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Get or create the CourseSchedule for the selected semester
        CourseSchedule schedule = ownerDepartment.getCourseSchedule(selectedSemester);
        if (schedule == null) {
            schedule = ownerDepartment.newCourseSchedule(selectedSemester);
        }

        // 5. Create the new CourseOffer
        CourseOffer newOffer = schedule.newCourseOffer(selectedCourse.getCOurseNumber());
        if (newOffer == null) {
            JOptionPane.showMessageDialog(this, "Failed to create the new course offer.", "System Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 6. Assign teacher and generate seats
        newOffer.AssignAsTeacher(selectedFaculty);
        newOffer.generatSeats(seatLimit);

        // 7. Provide feedback and navigate back
        JOptionPane.showMessageDialog(this, "Course Offering created successfully!");

        // Go back to the list panel automatically
        btnBackActionPerformed(null);
    }

    private Department findDepartmentForCourse(Course targetCourse) {
        for (Department dept : business.getUniversity().getDepartmentDirectory().getDepartmentList()) {
            if (dept.getCourseCatalog().getCourseByNumber(targetCourse.getCOurseNumber()) != null) {
                return dept;
            }
        }
        return null; // Should not happen if data is consistent
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Course> comboCourse;
    private javax.swing.JComboBox<FacultyProfile> comboFaculty;
    private javax.swing.JComboBox<String> comboSemester;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblFaculty;
    private javax.swing.JLabel lblSeatLimit;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtSeatLimit;
    // End of variables declaration
}