/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import Business.Business;
import javax.swing.JPanel;
import java.awt.CardLayout;
/**
 *
 * @author Administrator
 */
public class RegistrarWorkAreaJPanel extends javax.swing.JPanel {
    private Business business;
    private JPanel CardSequencePanel; 
    /**
     * Creates new form RegistrarWorkAreaJPanel
     */
    public RegistrarWorkAreaJPanel(Business b, JPanel cardSequencePanel) {
        initComponents(); 
        this.business = b; 
        this.CardSequencePanel = cardSequencePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCourses = new javax.swing.JButton();
        btnManageEnrollment = new javax.swing.JButton();
        btnFinancials = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();

        btnManageCourses.setText("ManageCourses");
        btnManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCoursesActionPerformed(evt);
            }
        });

        btnManageEnrollment.setText("ManageEnrollment");
        btnManageEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnrollmentActionPerformed(evt);
            }
        });

        btnFinancials.setText("Financials");
        btnFinancials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancialsActionPerformed(evt);
            }
        });

        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageCourses)
                    .addComponent(btnFinancials))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReports)
                    .addComponent(btnManageEnrollment))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCourses)
                    .addComponent(btnManageEnrollment))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinancials)
                    .addComponent(btnReports))
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCoursesActionPerformed
         ManageCourseOfferingsJPanel panel = new ManageCourseOfferingsJPanel(business, CardSequencePanel);
         CardSequencePanel.add("ManageCourseOfferingsJPanel", panel);
         CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
         layout.show(CardSequencePanel, "ManageCourseOfferingsJPanel");
    }//GEN-LAST:event_btnManageCoursesActionPerformed

    private void btnManageEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnrollmentActionPerformed
        ManageStudentEnrollmentJPanel panel = new ManageStudentEnrollmentJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageStudentEnrollmentJPanel", panel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.show(CardSequencePanel, "ManageStudentEnrollmentJPanel");
    }//GEN-LAST:event_btnManageEnrollmentActionPerformed

    private void btnFinancialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancialsActionPerformed
        ManageTuitionJPanel panel = new ManageTuitionJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageTuitionJPanel", panel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.show(CardSequencePanel, "ManageTuitionJPanel");
    }//GEN-LAST:event_btnFinancialsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
       ManageReportsJPanel panel = new ManageReportsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageReportsJPanel", panel);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.show(CardSequencePanel, "ManageReportsJPanel");
    }//GEN-LAST:event_btnReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinancials;
    private javax.swing.JButton btnManageCourses;
    private javax.swing.JButton btnManageEnrollment;
    private javax.swing.JButton btnReports;
    // End of variables declaration//GEN-END:variables
}
